### ISSUE TITLE
Morning session 5/11

### ISSUE THREAD

**Issue by Fig77** [kalavhan/Desgin-teardown#2]

**Comment by Rhelli** [comment]
- Good to see you are using font-face! You should however only need to import .woff2 and .woff. Woff1 + 2 are supported by every modern browser (.ttf is supported by android 2 - 4.3 which only makes up 1% of internet browsing), .eot can optionally be used for IE 8 and backwards compatibility and the rest's job is done by woff1 + 2. Loading too many fonts will slows your sites loading time down significantly.

- Avoid empty classes and comments (although stickler should catch these)

- Instead of using '.article-styling:nth-of-type(1)..(2)..(3)..(4)', you can use a range selector. E.g. '.article-styling:nth-child(-n+4)';

- Otherwise, good work on the page! The layouts really clean and everything should all slot into place!
